# Generated by Django 5.0.2 on 2024-03-31 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
